sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: skyAdministrator
    password: 2048433880zzb
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tRjQCBPMP2GZZPEKBrq
    access-key-secret: JQhI1PNfkNkW0yMxLhr8SQL4i9su1h
    bucket-name: zzb-sky
  redis:
    host: localhost
    password: 2048433880zzb
    port: 6379
    database: 0
  wechat:
    appid: wxcf848b8acb49d37f
    secret: cd92d5c6e8c6e1bbbebc47f398b9b659
